<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Models\Permission;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = [
            ['name' => 'profit_loss_report.view'],
            ['name' => 'direct_sell.access'],
            ['name' => 'product.opening_stock'],
            ['name' => 'crud_all_bookings'],
            ['name' => 'crud_own_bookings'],
            ['name' => 'access_default_selling_price'],
            ['name' => 'purchase.payments'],
            ['name' => 'sell.payments'],
            ['name' => 'edit_product_price_from_sale_screen'],
            ['name' => 'edit_product_discount_from_sale_screen'],
            ['name' => 'roles.view'],
            ['name' => 'roles.create'],
            ['name' => 'roles.update'],
            ['name' => 'roles.delete'],
            ['name' => 'account.access'],
            ['name' => 'discount.access'],
            ['name' => 'view_purchase_price'],
            ['name' => 'view_own_sell_only'],
            ['name' => 'edit_product_discount_from_pos_screen'],
            ['name' => 'edit_product_price_from_pos_screen'],
            ['name' => 'access_shipping'],
            ['name' => 'purchase.update_status'],
            ['name' => 'list_drafts'],
            ['name' => 'list_quotations'],
            ['name' => 'view_cash_register'],
            ['name' => 'close_cash_register'],
            ['name' => 'print_invoice'],
            ['name' => 'user.view'],
            ['name' => 'user.create'],
            ['name' => 'user.update'],
            ['name' => 'user.delete'],
            ['name' => 'supplier.view'],
            ['name' => 'supplier.create'],
            ['name' => 'supplier.update'],
            ['name' => 'supplier.delete'],
            ['name' => 'customer.view'],
            ['name' => 'customer.create'],
            ['name' => 'customer.update'],
            ['name' => 'customer.delete'],
            ['name' => 'product.view'],
            ['name' => 'product.create'],
            ['name' => 'product.update'],
            ['name' => 'product.delete'],
            ['name' => 'purchase.view'],
            ['name' => 'purchase.create'],
            ['name' => 'purchase.update'],
            ['name' => 'purchase.delete'],
            ['name' => 'sell.view'],
            ['name' => 'sell.create'],
            ['name' => 'sell.update'],
            ['name' => 'sell.delete'],
            ['name' => 'purchase_n_sell_report.view'],
            ['name' => 'contacts_report.view'],
            ['name' => 'stock_report.view'],
            ['name' => 'tax_report.view'],
            ['name' => 'trending_product_report.view'],
            ['name' => 'register_report.view'],
            ['name' => 'sales_representative.view'],
            ['name' => 'expense_report.view'],
            ['name' => 'business_settings.access'],
            ['name' => 'barcode_settings.access'],
            ['name' => 'invoice_settings.access'],
            ['name' => 'brand.view'],
            ['name' => 'brand.create'],
            ['name' => 'brand.update'],
            ['name' => 'brand.delete'],
            ['name' => 'tax_rate.view'],
            ['name' => 'tax_rate.create'],
            ['name' => 'tax_rate.update'],
            ['name' => 'tax_rate.delete'],
            ['name' => 'unit.view'],
            ['name' => 'unit.create'],
            ['name' => 'unit.update'],
            ['name' => 'unit.delete'],
            ['name' => 'category.view'],
            ['name' => 'category.create'],
            ['name' => 'category.update'],
            ['name' => 'category.delete'],
            ['name' => 'expense.access'],
            ['name' => 'access_all_locations'],
            ['name' => 'dashboard.data'],
            ['name' => 'essentials.create_message'],

            ['name' => 'essentials.view_message'],
            ['name' => 'essentials.approve_leave'],
            ['name' => 'essentials.assign_todos'],
            ['name' => 'essentials.add_allowance_and_deduction'],
            ['name' => 'manufacturing.access_recipe'],
            ['name' => 'manufacturing.access_production'],
            ['name' => 'manufacturing.add_recipe'],
            ['name' => 'manufacturing.edit_recipe'],
            ['name' => 'woocommerce.syc_categories'],
            ['name' => 'woocommerce.sync_products'],
            ['name' => 'woocommerce.sync_orders'],
            ['name' => 'woocommerce.map_tax_rates'],
            ['name' => 'woocommerce.access_woocommerce_api_settings'],
            ['name' => 'repair.create'],
            ['name' => 'repair.update'],
            ['name' => 'repair.view'],
            ['name' => 'repair.delete'],
            ['name' => 'repair_status.update'],
            ['name' => 'repair_status.access'],
            ['name' => 'supplier.view_own'],
            ['name' => 'customer.view_own'],
            ['name' => 'view_own_purchase'],
            ['name' => 'direct_sell.delete'],
            ['name' => 'view_commission_agent_sell'],
            ['name' => 'access_sell_return'],
            ['name' => 'edit_invoice_number'],
            ['name' => 'access_own_shipping'],
            ['name' => 'access_commission_agent_shipping'],
            ['name' => 'view_product_stock_value'],
            ['name' => 'view_own_expense'],
            ['name' => 'access_printers'],
            ['name' => 'job_sheet.create'],
            ['name' => 'job_sheet.edit'],
            ['name' => 'job_sheet.delete'],
            ['name' => 'job_sheet.view_assigned'],
            ['name' => 'job_sheet.view_all'],
            ['name' => 'superadmin.access_package_subscriptions'],
            ['name' => 'access_types_of_service'],
            ['name' => 'project.create_project'],
            ['name' => 'project.edit_project'],
            ['name' => 'project.delete_project'],
            ['name' => 'selling_price_group.1'],
            ['name' => 'selling_price_group.2'],
            ['name' => 'selling_price_group.3'],
            ['name' => 'selling_price_group.4'],
            ['name' => 'selling_price_group.5'],
            ['name' => 'selling_price_group.6'],
            ['name' => 'selling_price_group.7'],
            ['name' => 'selling_price_group.8'],
            ['name' => 'selling_price_group.9'],
            ['name' => 'selling_price_group.10'],
            ['name' => 'selling_price_group.11'],
            ['name' => 'selling_price_group.12'],
            ['name' => 'direct_sell.view'],
            ['name' => 'direct_sell.update'],
            ['name' => 'expense.add'],
            ['name' => 'expense.edit'],
            ['name' => 'expense.delete'],
            ['name' => 'all_expense.access'],
            ['name' => 'crm.access_all_schedule'],
            ['name' => 'crm.access_own_schedule'],
            ['name' => 'crm.access_all_leads'],
            ['name' => 'crm.access_own_leads'],
            ['name' => 'crm.access_all_campaigns'],
            ['name' => 'crm.access_own_campaigns'],
            ['name' => 'crm.access_contact_login'],
            ['name' => 'crm.access_sources'],
            ['name' => 'crm.access_life_stage'],
            ['name' => 'essentials.crud_own_leave'],
            ['name' => 'essentials.view_own_attendance'],
            ['name' => 'essentials.view_allowance_and_deduction'],
            ['name' => 'essentials.crud_department'],
            ['name' => 'essentials.crud_designation'],
            ['name' => 'selling_price_group.13'],
            ['name' => 'selling_price_group.14'],
            ['name' => 'selling_price_group.15'],
            ['name' => 'selling_price_group.16'],
            ['name' => 'selling_price_group.17'],
            ['name' => 'selling_price_group.18'],
            ['name' => 'selling_price_group.19'],
            ['name' => 'essentials.crud_leave_type'],
            ['name' => 'essentials.crud_all_leave'],
            ['name' => 'essentials.crud_all_attendance'],
            ['name' => 'selling_price_group.20'],
            ['name' => 'selling_price_group.21'],
            ['name' => 'selling_price_group.22'],
            ['name' => 'selling_price_group.23'],
            ['name' => 'purchase_order.view_own'],
            ['name' => 'purchase_order.view_all'],
            ['name' => 'purchase_order.create'],
            ['name' => 'purchase_order.update'],
            ['name' => 'purchase_order.delete'],
            ['name' => 'so.view_own'],
            ['name' => 'so.view_all'],
            ['name' => 'so.create'],
            ['name' => 'so.update'],
            ['name' => 'so.delete'],
            ['name' => 'selling_price_group.24'],
            ['name' => 'selling_price_group.25'],
            ['name' => 'selling_price_group.26'],
            ['name' => 'selling_price_group.27'],
            ['name' => 'selling_price_group.28'],
            ['name' => 'selling_price_group.29'],
            ['name' => 'view_paid_sells_only'],
            ['name' => 'view_due_sells_only'],
            ['name' => 'view_partial_sells_only'],
            ['name' => 'view_overdue_sells_only'],
            ['name' => 'access_own_sell_return'],
            ['name' => 'quotation.update'],
            ['name' => 'quotation.delete'],
            ['name' => 'access_pending_shipments_only'],
            ['name' => 'quotation.view_own'],
            ['name' => 'quotation.view_all'],
            ['name' => 'essentials.allow_users_for_attendance_from_web'],
            ['name' => 'essentials.allow_users_for_attendance_from_api'],
            ['name' => 'customer_with_no_sell_one_year'],
            ['name' => 'draft.update'],
            ['name' => 'draft.view_all'],
            ['name' => 'selling_price_group.30'],
            ['name' => 'access_tables'],
            ['name' => 'selling_price_group.31'],
            ['name' => 'selling_price_group.32'],
            ['name' => 'selling_price_group.33'],
            ['name' => 'selling_price_group.34'],
            ['name' => 'selling_price_group.35'],
            ['name' => 'selling_price_group.36'],
            ['name' => 'draft.delete'],
            ['name' => 'draft.view_own'],
            ['name' => 'selling_price_group.37'],
            ['name' => 'selling_price_group.38'],
            ['name' => 'selling_price_group.39'],
            ['name' => 'selling_price_group.40'],
            ['name' => 'customer_with_no_sell_three_month'],
            ['name' => 'customer_with_no_sell_one_month'],
            ['name' => 'selling_price_group.41'],
            ['name' => 'selling_price_group.42'],
            ['name' => 'selling_price_group.43'],
            ['name' => 'selling_price_group.44'],
            ['name' => 'selling_price_group.45'],
            ['name' => 'selling_price_group.46'],
            ['name' => 'selling_price_group.47'],
            ['name' => 'selling_price_group.48'],
            ['name' => 'selling_price_group.49'],
            ['name' => 'selling_price_group.50'],
            ['name' => 'selling_price_group.51'],
            ['name' => 'selling_price_group.52'],
            ['name' => 'selling_price_group.53'],
            ['name' => 'selling_price_group.54'],
            ['name' => 'selling_price_group.55'],
            ['name' => 'selling_price_group.56'],
            ['name' => 'selling_price_group.57'],
            ['name' => 'selling_price_group.58'],
            ['name' => 'selling_price_group.59'],
            ['name' => 'all_payroll'],
            ['name' => 'essentials.all_payroll'],
            ['name' => 'essentials.delete_leave'],

            ['name' => 'banners.view'],
            ['name' => 'banners.create'],
            ['name' => 'banners.update'],
            ['name' => 'banners.delete'],

            ['name' => 'orders.view'],
            ['name' => 'orders.create'],
            ['name' => 'orders.update'],
            ['name' => 'orders.delete'],
            ['name' => 'orders.changeStatus'],
            ['name' => 'orders.changePayment'],
            ['name' => 'orders.reports'],

            ['name' => 'orders_refund.view'],
            ['name' => 'orders_refund.create'],
            ['name' => 'orders_refund.update'],
            ['name' => 'orders_refund.delete'],
            ['name' => 'orders_refund.changeStatus'],
            ['name' => 'orders_refund.changePayment'],

            ['name' => 'orders_transfer.view'],
            ['name' => 'orders_transfer.create'],
            ['name' => 'orders_transfer.update'],
            ['name' => 'orders_transfer.delete'],
            ['name' => 'orders_transfer.changeStatus'],
            ['name' => 'orders_transfer.changePayment'],

            ['name' => 'orders_cancellation.view'],
            ['name' => 'orders_cancellation.create'],
            ['name' => 'orders_cancellation.update'],
            ['name' => 'orders_cancellation.delete'],
            ['name' => 'orders_cancellation.changeStatus'],
            ['name' => 'orders_cancellation.changePayment'],

            ['name' => 'clients.view'],


            ['name' => 'deliveries.view'],
            ['name' => 'deliveries.view_all'],
            ['name' => 'deliveries.orders'],

            ['name' => 'applicationSettings.view'],
            ['name' => 'applicationSettings.dashboard'],


        ];

        foreach ($data as $d) {
            Permission::firstOrCreate(
                ['name' => $d['name'], 'guard_name' => 'web'],
                ['created_at' => now()]
            );
        }
    }
}
